name: Auto PR to Dev

on:
  push:
    branches:
      - "feature/*"  # Change this to match your feature branch pattern

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev  # The target branch
          branch: ${{ github.ref_name }}  # The branch that was pushed
          title: "Auto PR: ${{ github.ref_name }} → dev"
          body: "This PR was automatically created when changes were pushed."
